#STAGE 1
FROM node:22-alpine AS build
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npx nx build dp-admin
RUN npm prune --omit=dev --omit=optional --omit=peer --ignore-scripts

#STAGE 2
FROM nginx:1.17.1-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist/apps/dp-admin /usr/share/nginx/html  
