name: dp-front

services:
  student:
    hostname: dp-front-student
    build:
      context: .
      dockerfile: Dockerfile.student
    expose:
      - "80:80"
    networks:
      - front

  admin:
    hostname: dp-front-admin
    build:
      context: .
      dockerfile: Dockerfile.admin
    expose:
      - "80:80"
    networks:
      - front

networks:
  front:
    name: dp-front

