name: dp-front

services:
  student:
    build:
      context: .
      dockerfile: Dockerfile.student
    expose:
      - 8180
    ports:
      - "8180:80"

  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    expose:
      - 8280
    ports:
      - "8280:80"

