import { Company } from '@dp/admin/company/types';

export const companiesMock: ReadonlyArray<Company> = [
  {
    id: '1',
    name: 'Michael Palin',
    spokesman: 'Геннадий Павлович',
    contact: 'm.palin@montypython.com',
    vacancies: ['Funny'],
    vacanciesNumber: 1,
  },
  {
    id: '1',
    name: 'Eric Idle',
    spokesman: 'Геннадий Павлович',
    contact: 'e.idle@montypython.com',
    vacancies: ['Funny', 'Music'],
    vacanciesNumber: 1,
  },
  {
    id: '1',
    name: 'John Cleese',
    spokesman: 'Геннадий Павлович',
    contact: 'j.cleese@montypython.com',
    vacancies: ['Funny', 'Tall', 'Actor'],
    vacanciesNumber: 1,
  },
  {
    id: '1',
    name: 'Terry Jones',
    spokesman: 'Геннадий Павлович',
    contact: '',
    vacancies: ['Funny', 'Director'],
    vacanciesNumber: 1,
  },
  {
    id: '1',
    name: 'Terry Gilliam',
    spokesman: 'Геннадий Павлович',
    contact: 't.gilliam@montypython.com',
    vacancies: ['Funny', 'Director'],
    vacanciesNumber: 1,
  },
  {
    id: '1',
    name: 'Graham Chapman',
    spokesman: 'Геннадий Павлович',
    contact: '',
    vacancies: ['Funny', 'King Arthur'],
    vacanciesNumber: 1,
  },
  {
    id: '1',
    name: 'John Cleese',
    spokesman: 'Геннадий Павлович',
    contact: 'j.cleese@montypython.com',
    vacancies: ['Funny', 'Tall', 'Actor'],
    vacanciesNumber: 1,
  },
  {
    id: '1',
    name: 'John Cleese',
    spokesman: 'Геннадий Павлович',
    contact: 'j.cleese@montypython.com',
    vacancies: ['Funny', 'Tall', 'Actor'],
    vacanciesNumber: 1,
  },
  {
    id: '1',
    name: 'John Cleese',
    spokesman: 'Геннадий Павлович',
    contact: 'j.cleese@montypython.com',
    vacancies: ['Funny', 'Tall', 'Actor'],
    vacanciesNumber: 1,
  },
  {
    id: '1',
    name: 'John Cleese',
    spokesman: 'Геннадий Павлович',
    contact: 'j.cleese@montypython.com',
    vacancies: ['Funny', 'Tall', 'Actor'],
    vacanciesNumber: 1,
  },
  {
    id: '1',
    name: 'John Cleese',
    spokesman: 'Геннадий Павлович',
    contact: 'j.cleese@montypython.com',
    vacancies: ['Funny', 'Tall', 'Actor'],
    vacanciesNumber: 1,
  },
  {
    id: '1',
    name: 'John Cleese',
    spokesman: 'Геннадий Павлович',
    contact: 'j.cleese@montypython.com',
    vacancies: ['Funny', 'Tall', 'Actor'],
    vacanciesNumber: 1,
  },
];
